spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xyd
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /xyd
  port: 8003